# For convenience, set and use env config values from here and do not push them
# to heroku via `figaro heroku:set -e production`.
#
# RACK_ENV, RAILS_ENV and some others are set directly on Heroku. The rest are here.

support_email: "info@churchofsouthland.com"
# make it easier to spot our log messages
logging_sigil: "{MMMMMMMMMMMMMMMMMMMM}"
# devise friendly_token length, must be <= 20
autogen_password_length: "12"

default_time_zone: 'Pacific Time (US & Canada)'

# 626 mandate parse-able start date in UTC
mandate_start_date: 'Sun, 07 Mar 2016 00:00:00 PST -08:00'
# 626 mandate parse-able finish date in UTC
mandate_finish_date: 'Fri, 12 Mar 2016 23:59:59 PST -08:00'

# date calendar starts on
calendar_start_date: 'Sat, 06 Mar 2016 00:00:00 PST -08:00'
# last starting week to show on calendar
calendar_last_date: 'Sat, 13 Mar 2016 00:00:00 PST -08:00'

# set default here but we don't want to be using rollbar in anything other than prod/stage
rollbar_access_token: 'foo'

# environment specific values start here
development:
  MAILTRAP_USERNAME: "foo"
  MAILTRAP_PASSWORD: "foo"

test:
  foo: 'p'

production:
  rollbar_access_token: 'foo'
